"""
Canonical Reason Codes for Reconciliation and Exception Classification.
Defines immutable standard codes used across backend matching and frontend presentation.
"""


class CanonicalReasonCode:
    # Deterministic Matches
    EXACT_3_WAY_MATCH = "EXACT_3_WAY_MATCH"
    FEE_RECONCILED = "FEE_RECONCILED"
    FEE_VARIANCE = "FEE_VARIANCE"
    TIMING_DIFFERENCE = "TIMING_DIFFERENCE"
    MANY_TO_ONE_MATCH = "MANY_TO_ONE_MATCH"
    ONE_TO_MANY_MATCH = "ONE_TO_MANY_MATCH"

    # Discrepancies & Reviews
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    REFERENCE_MISMATCH = "REFERENCE_MISMATCH"
    CUSTOMER_MISMATCH = "CUSTOMER_MISMATCH"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    DATE_OUTSIDE_TOLERANCE = "DATE_OUTSIDE_TOLERANCE"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    MATERIALITY_EXCEEDED = "MATERIALITY_EXCEEDED"

    # Missing & Orphan Exceptions
    MISSING_BANK_SETTLEMENT = "MISSING_BANK_SETTLEMENT"
    MISSING_GATEWAY_TRANSACTION = "MISSING_GATEWAY_TRANSACTION"
    MISSING_INVOICE = "MISSING_INVOICE"
    DUPLICATE_TRANSACTION = "DUPLICATE_TRANSACTION"
    UNALLOCATED_DEPOSIT = "UNALLOCATED_DEPOSIT"
